namespace: janleshy

name: homeassistant

version: 1.6.0

readme: README.md

authors:
  - Jan Roepke (JanLeshy)

description: A Collection to install and manage homeassistant and additional Software

license_file: LICENSE

tags:
  - homeassistant
  - automation
  - hass
  - esphome
  - homeautomation
  - iot
  - esp32
  - esp8266
  - raspberrypi


dependencies: {}

repository: https://github.com/janleshy/ansible-collection-homeassistant

documentation: https://github.com/janleshy/ansible-collection-homeassistant/blob/main/README.md

homepage: https://github.com/janleshy/ansible-collection-homeassistant

issues: https://github.com/janleshy/ansible-collection-homeassistant/issues

build_ignore: []

