---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install specific packages
  ansible.builtin.package:
    name:
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - bluez
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - zlib1g-dev
      - autoconf
      - build-essential
      - libopenjp2-7
      - libtiff6
      - libturbojpeg0-dev
      - tzdata
      - ffmpeg
      - liblapack3
      - liblapack-dev
      - libatlas-base-dev
      - libsqlite3-dev
      - libbz2-dev
    state: present
