---
- name: Stop running homeassistant service
  ansible.builtin.command: echo "Stop Home Assistant"
  changed_when: false
  notify: "Stop Home Assistant"

- name: FLush Handlers
  ansible.builtin.meta: flush_handlers


- name: Create ha_backup_restore directory
  ansible.builtin.file:
    path: "/home/{{ ha_user }}/ha_backup_restore"
    state: directory
    mode: "02775"
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"

- name: Backup current homeassistant config directory
  community.general.archive:
    path: "/home/{{ ha_user }}/.homeassistant"
    dest: "/home/{{ ha_user }}/ha_backup_restore/homeassistant_ansible_backup{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}.tgz"
    remove: true
    mode: "02775"
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"

- name: Copy backupfile to remote server
  ansible.builtin.copy:
    src: "{{ ha_backup }}"
    dest: "/home/{{ ha_user }}/ha_backup_restore"
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    mode: preserve

- name: Create folder for untar
  ansible.builtin.file:
    path: "/home/{{ ha_user }}/ha_backup_restore/{{ ha_backup[:-4] }}"
    state: directory
    mode: "02775"
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"

- name: Untar backupfile on remote
  ansible.builtin.unarchive:
    src: /home/{{ ha_user }}/ha_backup_restore/{{ ha_backup | basename }}
    dest: /home/{{ ha_user }}/ha_backup_restore/{{ ha_backup[:-4] }}/
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    remote_src: true

- name: Untar the homeassistant.tar.gz file
  ansible.builtin.unarchive:
    src: "/home/{{ ha_user }}/ha_backup_restore/{{ ha_backup[:-4] }}/homeassistant.tar.gz"
    dest: "/home/{{ ha_user }}/ha_backup_restore/{{ ha_backup[:-4] }}"
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    remote_src: true

- name: Copy files from data folder to ha_conf_dir
  ansible.builtin.copy:
    src: "/home/{{ ha_user }}/ha_backup_restore/{{ ha_backup[:-4] }}/data/"
    dest: "/home/{{ ha_user }}/.homeassistant"
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    directory_mode: true
    remote_src: true
    mode: preserve

- name: Remove ha_backup_restore folder
  ansible.builtin.file:
    path: "/home/{{ ha_user }}/ha_backup_restore/{{ ha_backup[:-4] }}"
    state: absent
  notify: "Start Home Assistant"
