---
- name: Install required packages
  ansible.builtin.import_tasks: install_dependencies.yml
  tags:
      - dependencies
      - esphome

- name: Set firewall rule
  ansible.builtin.import_tasks: firewall.yml
  tags:
      - firewall
      - esphome

- name: Create user and Group
  ansible.builtin.import_tasks: create_user_and_group.yml
  tags:
      - user_group
      - esphome

- name: Create environment and config directory
  ansible.builtin.import_tasks: create_required_directory.yml
  tags:
      - environment
      - esphome

- name: Installation tasks for ESPHome
  ansible.builtin.import_tasks: install_esphome.yml
  tags:
      - installation
      - esphome

- name: Change ownership of esphome directory to {{ ha_user }}
  ansible.builtin.import_tasks: change_ownership.yml
  tags:
      - esphome
      - change_owner

- name: Create systemd service
  ansible.builtin.import_tasks: create_systemd_service.yml
  tags:
      - systemd
      - esphome
